name: Coverage
on:
  pull_request: # only activates for pull requests
    branches: ["main"]
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      # this moves to the directory of dotting!
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Test and coverage
        run: yarn test --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info

      - name: Save PR number to file
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Upload PR number
        uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: pr_number.txt
