name: Delete PR Preview

on:
  pull_request:
    types:
      - closed

permissions:
  pull-requests: write
  contents: write

concurrency: preview-${{ github.event.pull_request.number }}

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/
          preview-branch: preview
          custom-url: dotting-preview.netlify.app
          token: ${{ secrets.GITHUB_TOKEN }}
          action: remove
