name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

concurrency: preview-${{ github.event.pull_request.number }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn run storybook:build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/
          preview-branch: preview
          custom-url: dotting-preview.netlify.app
          token: ${{ secrets.GITHUB_TOKEN }}
          action: deploy
